name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  
  jobs:
    build:
      name: Jobs to updates datas
      run-on: ubuntu-latest
      steps:
        # Snake Animation
    - uses: Platane/snk@master
      id: snake-gif
      with:
      github-user-name: Renan-Scola
      svg_out_patch: dist/github-contribuition-grid-snake.svg
      
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with: 
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    
